format_version: 10
pipelines:
  terraform-create:
    group: create
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2ae7d73:
        git: https://github.com/devps23/expenseterraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - terraform-stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          terraform-apply:
            timeout: 0
            tasks:
            - exec: { command: terraform,  arguments: [ "init" ], run_if: passed }
            - exec: { command: terraform,  arguments: [ "apply","-var-file=load_variables/load_Value.tfvars","-auto-approve" ], run_if: passed }




